/**
 * ══════════════════════════════════════════════════════════════════════
 *  MÉFAITS DES CARTES — TICKET CRICKET 2026
 *  Numérotation : 1-63 Investisseurs | 64-116 Contribuables | 117-324 Contraventions
 * ══════════════════════════════════════════════════════════════════════
 */

const CARD_MEFAITS: Record<number, string> = {
  // ── INVESTISSEURS (1-63) ─────────────────────────────────────────────────
  1: "Ticket au prochain criminel",
  2: "Ticket au prochain criminel",
  3: "Ticket au prochain criminel",
  4: "Ticket au prochain criminel",
  5: "Ticket au prochain criminel",
  6: "Ticket au prochain criminel",
  7: "Ticket au prochain criminel",
  8: "Ticket au prochain criminel",
  9: "Ticket au prochain criminel",
  10: "Ticket au prochain criminel",
  11: "Ticket au prochain criminel",
  12: "Ticket au prochain criminel",
  13: "Ticket au prochain criminel",
  14: "Ticket au prochain criminel",
  15: "Ticket au prochain criminel",
  16: "Ticket au prochain criminel",
  17: "Ticket au prochain criminel",
  18: "Ticket au prochain criminel",
  19: "Ticket au prochain criminel",
  20: "Ticket au prochain criminel",
  21: "Ticket au prochain criminel",
  22: "Ticket au prochain criminel",
  23: "Ticket au prochain criminel",
  24: "Ticket au prochain criminel",
  25: "Ticket au prochain criminel",
  26: "Ticket au prochain criminel",
  27: "Ticket au prochain criminel",
  28: "Ticket au prochain criminel",
  29: "Ticket au prochain criminel",
  30: "Ticket au prochain criminel",
  31: "Ticket au prochain criminel",
  32: "Ticket au prochain criminel",
  33: "Ticket au prochain criminel",
  34: "Ticket au prochain criminel",
  35: "Ticket au prochain criminel",
  36: "Ticket au prochain criminel",
  37: "Ticket au prochain criminel",
  38: "Ticket au prochain criminel",
  39: "Ticket au prochain criminel",
  40: "Ticket au prochain criminel",
  41: "Ticket au prochain criminel",
  42: "Ticket au prochain criminel",
  43: "Ticket au prochain criminel",
  44: "Ticket au prochain criminel",
  45: "Ticket au prochain criminel",
  46: "Ticket au prochain criminel",
  47: "Ticket au prochain criminel",
  48: "Ticket au prochain criminel",
  49: "Ticket au prochain criminel",
  50: "Ticket au prochain criminel",
  51: "Ticket au prochain criminel",
  52: "Ticket au prochain criminel",
  53: "Ticket au prochain criminel",
  54: "Ticket au prochain criminel",
  55: "Ticket au prochain criminel",
  56: "Ticket au prochain criminel",
  57: "Ticket au prochain criminel",
  58: "Ticket au prochain criminel",
  59: "Ticket au prochain criminel",
  60: "Ticket au prochain criminel",
  61: "Ticket au prochain criminel",
  62: "Ticket au prochain criminel",
  63: "Ticket au prochain criminel",
  // ── CONTRIBUABLES (64-116) ──────────────────────────────────────────────
  64: "Tu connais par cœur les paroles de la chanson Gangnam Style",
  65: "Tu es partis acheté du lait mais t\'es quand même revenu à la maison",
  66: "Tu cherches ton téléphone… avec ton téléphone dans la main",
  67: "Ton bodycount mérites d\'être récompensé",
  68: "En karaoké, tu chantes mal, personne t\'écoutes mais au moins tes saoul mort à la fin",
  69: "T\'es tellement pauvre que te donner un autre ticket te ferais tomber en depression post-partum avec des effets post-traumatique",
  70: "On manquait de papier pour te donner un ticket",
  71: "Pas de ticket cette année, gentille petite chose, tu veux un bisou avec ça ?",
  72: "Tu es respectueux, jovial, souriant, par contre tu gosses tout le monde",
  73: "Tu n\'as pas encore fais de jokes douteuses sur la mère de tes amis",
  74: "Vu que tu prends ton ritalin à chaque jours, ca mérite d\'être une bonne action",
  75: "Car tu as compris l\'utilité de virer tes bobettes de bord pour eviter du lavage",
  76: "Tu as vomis sur les passager arrière du Goliath à la ronde, c\'était une mauvaise journée, mais au moins pas de ticket hein ?",
  77: "Car tu connais le nombre d\'orteils de Toutânkhamon",
  78: "Tu as reussis à avoir un rendez-vous médicale après 6 ans d\'attente",
  79: "Bravo pour avoir lacher l\'école à 15 ans",
  80: "Car tu as été gentil pour Noel",
  81: "Tu n\'as pas fais de cadeau de Noel cette année pour économiser de l\'argent et acheter un truc inutile",
  82: "Le policier savait pas lire",
  83: "Tu fais pitié",
  84: "Tu prends du café 2,2 comme quelqu\'un de normal et civilié",
  85: "Tu recycle comme un citoyen ecolo, intelligent et qui aime la soumission agressive",
  86: "Tu fais ta vaiselle comme une personne responsable, attentionné des autres et serviable pour le système qui te nourris et te loge",
  87: "Tu as chier comme jamais mais au moins ca sentait rien",
  88: "Tu as manifesté contre le referendum",
  89: "Tu as écouté ta mère quand elle te disais toujours non car elle t\'aimais pas",
  90: "Tu as envoyé 5cents pour la fondations Tim Bits",
  91: "Bravo tu as gagné au 649, en 2006, tu as jamais réclamé ton dû car tu avais perdu ton billet",
  92: "Tu mets pas tes clignotant comme un citoyen avec du respect des codes de la routes",
  93: "Tu juges silencieusement les gens… puis tu culpabilises et ensuite tu te rends compte que t\'es seul, pas d\'amis, pas de yeux",
  94: "Tu crois que la guerre dans le monde est une bonne chose quand c\'est fait avec amour et dignité",
  95: "Tu vas au gym pour cruizer en esperant que quelqu\'un t\'aime",
  96: "Tu as permis a un esclave d\'avoir un bain 1 fois par mois",
  97: "Tu as porter un masque dans ton char en étant seul durant le covid, et tu le fais encore aujourd\'hui",
  98: "Tu as partie une secte mais au moins t\'es enregistrer au registre des entreprises",
  99: "Ton dossier était clean, à part en 1992 quand tu as acheter 42 guns sur le dark web mais sa passe",
  100: "Tu conduis un char électrique",
  101: "Tu conduis un bicycle et tu prends les rues au lieu des pistes cyclabe",
  102: "Ta schizophrénie sévère est un atout pour être un bon citoyen",
  103: "Je t\'aime",
  104: "Pour t\'être farcis une dinde, premier degré, c\'est hot",
  105: "T\'aime la poutine normal, pas d\'ajout, t\'es un civil respectable",
  106: "Pour avoir resister à un toutou avec des trous",
  107: "Pour avoir payer un pot de vins au policier en avance sexuel",
  108: "Écoute, l\'inflation frappe fort, t\'es dans marde, on te laisse une chance",
  109: "Pour avoir avoué que tu aimais te gargariser la gorge avec de l\'urine",
  110: "Pour avoir effacer ton disque dur avec des trucs louche dedans",
  111: "Pour t\'avoir réveiller comme un bon citoyen durant un Alerte Amber et avoir rien fait à part chialer",
  112: "Car tu pensais que le mush pouvait te donner des ailes, t\'es mort, mais au moins ta pub pour Redbull a marché",
  113: "Tu avais des rêves, t\'es rendu pauvre, triste, suicidaire, mais au moins tu joues à un jeu drôle, tiens cadeau",
  114: "Tu as reussit ton examen de conduite après ton 69e échec",
  115: "Parce que tu t\'appelles Chantale",
  116: "Tu crois en la réincarnation, mais seulement s\'il te manque des chromosomes",
  // ── CONTRAVENTIONS (117-324) ────────────────────────────────────────────
  117: "Petite quéquette, un petit ticket",
  118: "Tu parles français, mais tu fais au moins 16 erreurs dans le mot : français",
  119: "Pour avoir laissé un condom usagé sur la table de cuisine",
  120: "Pour avoir mis l\'air climatisé quand il faisait -38 dehors en hiver",
  121: "Pour avoir volé un sac de chips dans un dépanneur, mais avoir accusé le commis de te faire des avances",
  122: "Pour ne pas avoir mis de crème solaire quand ton animateur de camp t\'obligeait à en mettre",
  123: "Pour avoir pris un accent créole en imitant un singe",
  124: "Car tu as ri à « Tiens-moi par la barbichette »",
  125: "Pour avoir barré ta trottinette électrique avec du barbelé",
  126: "Pour avoir fait croire à tes amis que tu avais couché avec The Rock",
  127: "Pour avoir fait outrage à un policier qui essayait juste de te dire que manger du gypse, c\'était pas normal",
  128: "Pour avoir collé de la gomme sous ton pupitre, mais pas la tienne",
  129: "Tu croyais qu\'être sans-abri, c\'était un métier",
  130: "Tu as Michael Jackson dans ton arbre généalogique",
  131: "Être pansexuel ne fait pas de toi quelqu\'un autorisé à te farcir des oiseaux",
  132: "Pour avoir apprivoisé un pancréas en parfait état",
  133: "Pour t\'être évadé de prison de manière remarquable, c\'est très cool, mais bon, un ticket pour toi",
  134: "Pour avoir essayé de convertir des indigènes à la crypto",
  135: "Tes avis critiques sans arguments ne valent rien face à la puissance d\'une contravention",
  136: "Pour avoir fait partie d\'un système pyramidal sans avoir fait d\'argent",
  137: "Pour toi, Jack l\'Éventreur avait un motif valable",
  138: "Pour avoir flushé une personne qui avait un signe astrologique non compatible avec le tien",
  139: "Pour avoir envoyé 132456 Wizz sur MSN à ton ami décédé",
  140: "Pour avoir serré la main au corps exposé d\'un défunt que tu ne connaissais pas à des funérailles",
  141: "Pour avoir flashé tes seins à un chauffeur de bus scolaire",
  142: "Pour avoir vandalisé une animalerie, car tu pensais que les poissons pouvaient s\'enfuir eux aussi",
  143: "Tu pleures de désespoir quand quelqu\'un parle de Donald Trump en bien",
  144: "Pour avoir nommé ton hamster Reginald Sir Holocaust",
  145: "Pour avoir dit à un aveugle de regarder ailleurs si tu y étais",
  146: "Tu pensais qu\'en ayant tes maths fortes, tu pourrais te retrouver dans la même pièce qu\'Elon Musk",
  147: "10 + 40 x 2 - 20 =",
  148: "Pour avoir mis du popcorn dans ton urètre",
  149: "Pour être allé dans un camp de nudistes en disant que tu cherchais l\'amour",
  150: "Pour avoir mis une parodie pour adultes de Pat Patrouille sur YouTube Kids",
  151: "Car t\'es même pas capable de faire un grilled cheese sans oublier de mettre du Nutella",
  152: "Ton déficit mental ne te permet pas de comprendre le jeu",
  153: "T\'es un fan de K-POP",
  154: "Party Rock Anthem est, à l\'heure actuelle, toujours ta chanson préférée",
  155: "Tu parles à ton chat comme si t\'étais un retardé avec 4 ans d\'âge mental",
  156: "Tu caches des photos nues d\'animaux anthropomorphes dans ton cell",
  157: "Pour avoir vendu des organes de personnes blanches sur le marché noir",
  158: "Pour avoir manqué l\'autobus un mardi matin quand ta mère t\'avait dit de te lever pis d\'aller à l\'école, mais tu as 38 ans",
  159: "Pour le plaisir",
  160: "Pour avoir mis ton cul sur de l\'asphalte encore fraîche",
  161: "Tu ne sais pas lire",
  162: "Pour avoir été sur le Dark Web avec l\'ordi de la bibliothèque en accusant Cindy, 8 ans",
  163: "Pour être bon à l\'école, mais rien faire de ta vie",
  164: "Car tu commandes toujours la même chose au McDo",
  165: "Pour avoir touché les mamelons d\'un poisson rouge en pleine période de menstruation",
  166: "Car tu parles allemand, tu lis espagnol, tu chantes anglais, pis tu écris en hiéroglyphes",
  167: "Pour avoir écouté Baby Shark à répétition au gym en poussant 20 livres",
  168: "Pour avoir écrit ton nom sur un arbre avec la personne avec qui t\'étais en couple, mais aujourd\'hui elle t\'a trompé avec l\'arbre",
  169: "Pour avoir regardé chaque année sur ta Nintendo DS si tu avais la notif du BONNE FÊTE",
  170: "Pour avoir oublié de dire bonne fête à ton arrière-arrière-arrière-grand-père décédé",
  171: "Pour avoir osé dire que le trou dans la couche d\'ozone avait été causé par le 11 septembre",
  172: "Parce que tu penses que manger steak-frites va te faire devenir un homme",
  173: "Pour t\'être marié avec un singe en pensant que c\'était légal",
  174: "Pour avoir élevé une mouche de compagnie et l\'avoir appelée Rosalie",
  175: "Car tu as un gros cul",
  176: "Car tu pensais qu\'un monstre était sous ton lit quand t\'avais 6 ans, mais c\'était ton vieux mononcle",
  177: "Pour rien, tu n\'as rien fait, c\'est justement ce qui est bizarre",
  178: "Pour avoir caché du fentanyl dans des hot-dogs",
  179: "Car au lit tu fais l\'étoile, et tu es un homme",
  180: "Pour avoir un problème de masturbation abusif",
  181: "Pour avoir accroché un écureuil empaillé comme drapeau sur ton antenne de char",
  182: "Car tu as avoué sur Facebook que tu voulais faire sauter le Costco car Guylaine t\'a demandé ta facture à la sortie",
  183: "Pour avoir essayé de porter des bobettes XXX small tout en faisant cuire des Scott Towels sur le BBQ",
  184: "Car tu n\'as pas voté cette année en disant que si tu votes pas, au moins tu pourrais avoir de l\'aide sociale",
  185: "Ok",
  186: "Car tu le mérites tout simplement",
  187: "Pour avoir dit à tes amis que tu ne pouvais pas les voir ce soir, mais t\'étais en train de regarder Pornhub",
  188: "Pour avoir craché dans la face d\'un itinérant en disant qu\'il devait se laver",
  189: "Pour avoir changé ton statut de couple à célibataire 16 fois en 3 jours",
  190: "Pour avoir léché les parois d\'un ascenseur en te frottant le ventre en disant que tu aimais manger des crêpes le dimanche",
  191: "Pour avoir sucé ton cousin, fourré ta cousine et avoir beurré tes draps en pensant que tu pouvais être quelqu\'un de bien",
  192: "Car tu as commis un meurtre, le tien",
  193: "Car tu croyais que sauter en parachute tout nu en pissant en même temps serait une bonne demande en mariage",
  194: "Pour avoir volé du papier de toilette dans les toilettes de ta job car tu n\'en avais plus chez vous",
  195: "Imagine être cave à un point que tu pensais être capable de monter l\'Everest sans jambes",
  196: "Car il te manque un bras",
  197: "Car tu n\'as pas payé ton loyer",
  198: "Pour avoir appelé un taxi, t\'être poussé en marchant, avoir rappelé le taxi pour lui dire de venir te chercher chez lui",
  199: "Car tu as un problème de concentration quand on te parle",
  200: "Tu as essayé de parler avec un Asiatique en répétant soupe wonton sans arrêt",
  201: "Pour avoir abandonné tes enfants dans le bois en disant que tu reviendrais après l\'hiver",
  202: "Pour avoir fait du sexe anal en mangeant épicé la veille",
  203: "Pour avoir fait un clin d\'œil à un sac poubelle",
  204: "Pour avoir causé un accident de voiture sans voiture",
  205: "T\'es somnambule quand tu dors pas",
  206: "Pour avoir voulu faire une recherche Google et avoir oublié ce que tu cherchais",
  207: "Pour t\'être baigné dans le contenu d\'une toilette chimique",
  208: "Car tu as dit que les animés japonais c\'était pour les attardés et les gens qui se cherchent une maman",
  209: "Car t\'es pas capable de te décider si t\'es un homme, une femme ou un poulet roux avec du poil dans les yeux",
  210: "Pour avoir fait des jokes sur des gens disparus",
  211: "Car tu croyais qu\'être TDAH était un problème relié à la consommation de semence humaine de façon régulière",
  212: "Pour avoir publié ton pied unique à 3 orteils sur OnlyFans",
  213: "Pour avoir montré tes cartes Pokémon à des enfants de 5 ans, tu as 40 ans, grandis un peu",
  214: "Pour avoir essayé de mettre du duct tape sur ton anus",
  215: "Pour avoir sucé le doigt d\'une personne inconnue dans le métro de Montréal",
  216: "Pour avoir changé ton nom pour Roland XVII Poémélusse Moi L\'Anus Gastro-Entérite Premier du Nom",
  217: "Pour être embarqué dans le bus de ville avec une poupée gonflable en disant qu\'elle était enceinte",
  218: "Car tu t\'es stationné avec ton bicycle dans un stationnement pour handicapés",
  219: "Pour t\'être retrouvé complètement défoncé dans un dépanneur, en string, avec une perruque et une banane sur tes genoux",
  220: "Pour avoir fraudé un réseau de trafic de stupéfiants avec la carte de crédit de ta mère",
  221: "Pour avoir fait la chirurgie d\'une personne trans avec des tie-wraps, colle chaude et des clous",
  222: "Pour avoir regardé Titanic en boucle pendant 3 jours pour prouver que t\'étais incapable d\'avoir des émotions",
  223: "Car tu as dit à ta grand-mère que tu regrettais de l\'avoir traitée de vieille pute seulement à ses funérailles",
  224: "Pour avoir utilisé les bas de ton frère comme papier de toilette de secours",
  225: "Pour t\'être masturbé dans un pot de fleurs dans un cimetière",
  226: "Car pour toi une chèvre ne mérite pas d\'être premier ministre",
  227: "Pour avoir dit que la Russie était un peuple autochtone qui vénérait la poutine",
  228: "Pour avoir fait une demande de fiançailles avec une bague en bonbon",
  229: "Demander le consentement est important, surtout avec les animaux",
  230: "Pour avoir dit des propos racistes à une girafe au zoo de Granby",
  231: "Pour avoir mis tes doigts dans un blender Ninja",
  232: "Pour avoir serré la main à ton meilleur ami quand tu venais de te masturber",
  233: "Pour avoir volé une banque avec un pistolet à eau et un masque de Justin Trudeau",
  234: "Car tu n\'es pas vacciné",
  235: "Tu as gagné un item gratuit sur Temu. Tu ne le recevras jamais",
  236: "Tu veux quoi d\'autre ? Un bisou sur la fesse gauche ?",
  237: "Pour avoir touché un tas de marde sur le trottoir",
  238: "Car tu dis encore pipi, caca à 6 ans, ton immaturité doit payer ses actes",
  239: "Pour avoir recherché le mot « Enfants » dans les dossiers d\'Epstein",
  240: "T\'aimes pas le jeu ? Tant pis pour toi ! Tiens un beau ticket",
  241: "Tu devais de l\'argent à quelqu\'un pour le gaz",
  242: "Pour avoir beurré tes pantalons en recevant ton ticket",
  243: "Pour avoir oublié de payer tes impôts depuis 4 ans",
  244: "Pour avoir mangé des popsicles sensuellement",
  245: "Pour avoir fait une orgie avec tes peluches",
  246: "Pour avoir dit au juge que tu t\'appelais Joe Braquette Qui Vient de Karakette",
  247: "Pour t\'être fait une moustache avec les intestins d\'un cadavre",
  248: "Pour… ok je sais plus",
  249: "Pour avoir pleuré car tu n\'as pas eu de ticket",
  250: "Pour avoir eu un cancer, être guéri et ensuite dire à tout le monde que t\'es la résurrection de Jésus",
  251: "Tu pensais que cacher un corps dans une toilette de centre d\'achat pis le maquiller avec du Sephora, c\'était une bonne idée",
  252: "Tu utilises tes jouets sexuels comme ustensiles de cuisine",
  253: "Juste parce que ton QI est le même qu\'une mijoteuse Ricardo",
  254: "Pour avoir dit que François Legault était ton idole",
  255: "Pour avoir essayé de vendre des reins au Dollarama",
  256: "Tu as fait une commande Amazon, tu as demandé de te faire rembourser et tu as gardé le colis",
  257: "Pour avoir inventé une théorie disant que les tumeurs au cerveau, ça n\'existe pas, c\'est juste dans le but de faire de l\'argent",
  258: "Pour avoir joué de la flûte dans un orphelinat abandonné",
  259: "Pour avoir offert du lait maternel de contrebande à des bébés naissants",
  260: "Pour avoir fait l\'hélicoptère devant des policiers",
  261: "Pour avoir volé des panneaux de stop",
  262: "Pour avoir fait de la crazy carpet avec le corps de ton chat mort",
  263: "Pour t\'être touché la zigounette en pensant à Céline Dion",
  264: "Tu croyais au projet du 3e lien",
  265: "Pour avoir séquestré ton ex dans ta cave juste pour qu\'elle goûte tes biscuits bien cuits",
  266: "Tu pleures, c\'est correct je comprends, mais en même temps fallait pas toucher les seins du mannequin au Urban Planet",
  267: "Félicitations",
  268: "Car tu enregistres ta voisine en train de se faire défoncer par son amant et tu en fais des productions musicales sur Spotify",
  269: "Pour avoir chauffé un ski-doo pas de casque en kimono avec un chapeau de clown en criant « Liberté »",
  270: "Pour avoir dit que l\'humain est vraiment allé sur la lune",
  271: "Car tu cherchais ta virginité, mais tu l\'as perdue dans un Burger King avec 3 de tes chums",
  272: "Pour avoir essayé de chasser un tigre du Bengale dans un dépanneur avec une canne à pêche",
  273: "Pour avoir couché avec le père du père du père de ton père adoptif",
  274: "Je t\'ai vu coller tes crottes de nez sur le mur",
  275: "Pour avoir lancé du pain aux canards quand c\'était interdit",
  276: "Pour avoir trouvé des photos gluantes de Moïse Thériault dans ta chambre",
  277: "Fallait pas cacher tes magazines de porn dans le toaster",
  278: "Pour avoir acheté un dildo à deux bouts pour une blague, mais personne l\'a trouvé drôle",
  279: "Car tu faisais croire à ton père qu\'être viril signifiait être paraplégique",
  280: "Pour avoir sniffé du lave-vitre sur le comptoir du Shaker",
  281: "10 $ par voix dans ta tête",
  282: "Pour avoir touché les couilles d\'un cheval en lui chuchotant des belles promesses",
  283: "Pour avoir ri en voyant une personne en détresse en train de se noyer dans une piscine d\'acide",
  284: "Ça t\'apprendra à jamais fermer ta gueule",
  285: "Pour t\'être retrouvé endormi nu dans une garderie",
  286: "Pour avoir uriné sur les terres ancestrales de nos ancêtres à Coaticook",
  287: "Pour t\'être enlevé la vie en avertissant seulement ton boss que t\'aimais pas son attitude",
  288: "Car tu criais dans un restaurant tout ça pour avoir de l\'attention que tu n\'as jamais eue",
  289: "Le policier ne savait pas écrire",
  290: "Le policier se sentait gentil aujourd\'hui avec toi",
  291: "Car tu mérites de te faire fourrer par le système",
  292: "Tu pensais vraiment que les extraterrestres existaient ?",
  293: "Tu as voulu te partir un OnlyFans, mais t\'as oublié que t\'étais laid",
  294: "Car tu chauffais, saoul, pas de bras, pas de pantalons, yeux bandés avec une brassière",
  295: "T\'écoutes Scooby-Doo en swipant sur Tinder en espérant matcher avec Scooby, espèce de porc",
  296: "Pour avoir envoyé chier Dora l\'exploratrice en la contredisant",
  297: "T\'es mort et tu as laissé 1 million de dettes à ta famille qui t\'aimait pas",
  298: "Pour avoir demandé à ton coiffeur de te couper les cheveux, mais tu n\'existes pas",
  299: "Car tu crois que la Terre est plate",
  300: "Car tu crois que la Terre est ronde",
  301: "Car tu penses que les oiseaux sont des dinosaures",
  302: "Car tu pensais que la PCU allait te rendre riche",
  303: "Le policier devait remplir son mandat du mois",
  304: "Pour le plaisir de faire durer la partie, tu te manges un beau ticket",
  305: "Tu chauffes un F-150",
  306: "Tu penses que Sonic l\'hérisson voudra de toi, mais tu rêves en couleur",
  307: "Car tu croyais que croire était une croyance pour croire que tu croyais",
  308: "Tu crois à la vie après la mort",
  309: "Tu beurres tes toasts avec ta sueur",
  310: "C\'est grave de croire que de ne pas vendre de drogue aux enfants est une bonne idée",
  311: "Si tu étais moins désagréable, peut-être que tu n\'aurais pas un montant aussi élevé",
  312: "Tu te couches la nuit en prononçant des incantations sataniques",
  313: "Le policier ne se rappelle plus pourquoi tu devais avoir un ticket, mais pas le choix, tu dois payer",
  314: "Pour avoir essayé de discuter avec un autiste en langage des signes, mais c\'était des gang signs",
  315: "Tu as lu la Bible à l\'envers, tu mérites une contravention, fils de Satan",
  316: "Tu sais que de te percer les mamelons avec des chaînes de crânes en feu Harley-Davidson, c\'est pas légal ?",
  317: "Pour avoir dit le N-word",
  318: "Pour avoir monté le chauffage quand ton père te disait non",
  319: "Tu as voulu chier pis pisser en même temps, t\'as fini par vomir, péter et chanter Bohemian Rhapsody",
  320: "Tu t\'es perdu dans les rues du Vieux-Montréal, t\'as couché avec un crackhead, puis il t\'a laissé du tip",
  321: "T\'avais juste à pas voter libéral",
  322: "Sois meilleur, sois plus fort, la force du mental, pense mindset",
  323: "Pour avoir essayé de siffler l\'hymne national du Canada avec ton cul",
  324: "Malheureusement fallait bien que quelqu\'un se ramasse avec le ticket le plus élevé, félicitations champion",
};

export function getCardMefait(id: number): string | undefined {
  return CARD_MEFAITS[id];
}

export function hasCardMefait(id: number): boolean {
  return id in CARD_MEFAITS;
}
