/**
 * Mapping numéro de carte → texte du méfait.
 * Ce fichier est la source unique pour les descriptions de méfaits.
 * Remplir chaque entrée avec le texte fourni par l utilisateur.
 */

export const CARD_MEFAITS: Record<number, string> = {
  1: "Ticket au prochain criminel",
  2: "Ticket au prochain criminel",
  3: "Ticket au prochain criminel",
  4: "Ticket au prochain criminel",
  5: "Ticket au prochain criminel",
  6: "Ticket au prochain criminel",
  7: "Ticket au prochain criminel",
  8: "Ticket au prochain criminel",
  9: "Ticket au prochain criminel",
  10: "Ticket au prochain criminel",
  11: "Ticket au prochain criminel",
  12: "Ticket au prochain criminel",
  13: "Ticket au prochain criminel",
  14: "Ticket au prochain criminel",
  15: "Ticket au prochain criminel",
  16: "Ticket au prochain criminel",
  17: "Ticket au prochain criminel",
  18: "Ticket au prochain criminel",
  19: "Ticket au prochain criminel",
  20: "Ticket au prochain criminel",
  21: "Ticket au prochain criminel",
  22: "Ticket au prochain criminel",
  23: "Ticket au prochain criminel",
  24: "Ticket au prochain criminel",
  25: "Ticket au prochain criminel",
  26: "Ticket au prochain criminel",
  27: "Ticket au prochain criminel",
  28: "Ticket au prochain criminel",
  29: "Ticket au prochain criminel",
  30: "Ticket au prochain criminel",
  31: "Ticket au prochain criminel",
  32: "Ticket au prochain criminel",
  33: "Ticket au prochain criminel",
  34: "Ticket au prochain criminel",
  35: "Ticket au prochain criminel",
  36: "Ticket au prochain criminel",
  37: "Ticket au prochain criminel",
  38: "Ticket au prochain criminel",
  39: "Ticket au prochain criminel",
  40: "Ticket au prochain criminel",
  41: "Ticket au prochain criminel",
  42: "Ticket au prochain criminel",
  43: "Ticket au prochain criminel",
  44: "Ticket au prochain criminel",
  45: "Ticket au prochain criminel",
  46: "Ticket au prochain criminel",
  47: "Ticket au prochain criminel",
  48: "Ticket au prochain criminel",
  49: "Ticket au prochain criminel",
  50: "Ticket au prochain criminel",
  51: "Ticket au prochain criminel",
  52: "Ticket au prochain criminel",
  53: "Ticket au prochain criminel",
  54: "Ticket au prochain criminel",
  55: "Ticket au prochain criminel",
  56: "Ticket au prochain criminel",
  57: "Ticket au prochain criminel",
  58: "Ticket au prochain criminel",
  59: "Ticket au prochain criminel",
  60: "Ticket au prochain criminel",
  61: "Ticket au prochain criminel",
  62: "Ticket au prochain criminel",
  63: "Méfait à définir",
  64: "Méfait à définir",
  65: "Méfait à définir",
  66: "Méfait à définir",
  67: "Méfait à définir",
  68: "Méfait à définir",
  69: "Méfait à définir",
  70: "Méfait à définir",
  71: "Méfait à définir",
  72: "Méfait à définir",
  73: "Méfait à définir",
  74: "Méfait à définir",
  75: "Méfait à définir",
  76: "Méfait à définir",
  77: "Ticket au prochain criminel",
  78: "Méfait à définir",
  79: "Méfait à définir",
  80: "Méfait à définir",
  81: "Méfait à définir",
  82: "Méfait à définir",
  83: "Méfait à définir",
  84: "Méfait à définir",
  85: "Méfait à définir",
  86: "Méfait à définir",
  87: "Méfait à définir",
  88: "Méfait à définir",
  89: "Méfait à définir",
  90: "Méfait à définir",
  91: "Méfait à définir",
  92: "Méfait à définir",
  93: "Méfait à définir",
  94: "Méfait à définir",
  95: "Méfait à définir",
  96: "Méfait à définir",
  97: "Méfait à définir",
  98: "Méfait à définir",
  99: "Méfait à définir",
  100: "Méfait à définir",
  101: "Méfait à définir",
  102: "Méfait à définir",
  103: "Méfait à définir",
  104: "Méfait à définir",
  105: "Méfait à définir",
  106: "Méfait à définir",
  107: "Méfait à définir",
  108: "Méfait à définir",
  109: "Méfait à définir",
  110: "Méfait à définir",
  111: "Méfait à définir",
  112: "Méfait à définir",
  113: "Méfait à définir",
  114: "Méfait à définir",
  115: "Méfait à définir",
  116: "Méfait à définir",
  117: "Méfait à définir",
  118: "Méfait à définir",
  119: "Méfait à définir",
  120: "Méfait à définir",
  121: "Méfait à définir",
  122: "Méfait à définir",
  123: "Méfait à définir",
  124: "Méfait à définir",
  125: "Méfait à définir",
  126: "Méfait à définir",
  127: "Méfait à définir",
  128: "Méfait à définir",
  129: "Méfait à définir",
  130: "Méfait à définir",
  131: "Méfait à définir",
  132: "Méfait à définir",
  133: "Méfait à définir",
  134: "Méfait à définir",
  135: "Méfait à définir",
  136: "Méfait à définir",
  137: "Méfait à définir",
  138: "Méfait à définir",
  139: "Méfait à définir",
  140: "Méfait à définir",
  141: "Méfait à définir",
  142: "Méfait à définir",
  143: "Méfait à définir",
  144: "Méfait à définir",
  145: "Méfait à définir",
  146: "Méfait à définir",
  147: "Méfait à définir",
  148: "Méfait à définir",
  149: "Méfait à définir",
  150: "Méfait à définir",
  151: "Méfait à définir",
  152: "Méfait à définir",
  153: "Méfait à définir",
  154: "Méfait à définir",
  155: "Méfait à définir",
  156: "Méfait à définir",
  157: "Méfait à définir",
  158: "Méfait à définir",
  159: "Méfait à définir",
  160: "Méfait à définir",
  161: "Méfait à définir",
  162: "Méfait à définir",
  163: "Méfait à définir",
  164: "Méfait à définir",
  165: "Méfait à définir",
  166: "Méfait à définir",
  167: "Méfait à définir",
  168: "Méfait à définir",
  169: "Méfait à définir",
  170: "Méfait à définir",
  171: "Méfait à définir",
  172: "Méfait à définir",
  173: "Méfait à définir",
  174: "Méfait à définir",
  175: "Méfait à définir",
  176: "Méfait à définir",
  177: "Méfait à définir",
  178: "Méfait à définir",
  179: "Méfait à définir",
  180: "Méfait à définir",
  181: "Méfait à définir",
  182: "Méfait à définir",
  183: "Méfait à définir",
  184: "Méfait à définir",
  185: "Méfait à définir",
  186: "Méfait à définir",
  187: "Méfait à définir",
  188: "Méfait à définir",
  189: "Méfait à définir",
  190: "Méfait à définir",
  191: "Méfait à définir",
  192: "Méfait à définir",
  193: "Méfait à définir",
  194: "Méfait à définir",
  195: "Méfait à définir",
  196: "Méfait à définir",
  197: "Méfait à définir",
  198: "Méfait à définir",
  199: "Méfait à définir",
  200: "Méfait à définir",
  201: "Méfait à définir",
  202: "Méfait à définir",
  203: "Méfait à définir",
  204: "Méfait à définir",
  205: "Méfait à définir",
  206: "Méfait à définir",
  207: "Méfait à définir",
  208: "Méfait à définir",
  209: "Méfait à définir",
  210: "Méfait à définir",
  211: "Méfait à définir",
  212: "Méfait à définir",
  213: "Méfait à définir",
  214: "Méfait à définir",
  215: "Méfait à définir",
  216: "Méfait à définir",
  217: "Méfait à définir",
  218: "Méfait à définir",
  219: "Méfait à définir",
  220: "Méfait à définir",
  221: "Méfait à définir",
  222: "Méfait à définir",
  223: "Méfait à définir",
  224: "Méfait à définir",
  225: "Méfait à définir",
  226: "Méfait à définir",
  227: "Méfait à définir",
  228: "Méfait à définir",
  229: "Méfait à définir",
  230: "Méfait à définir",
  231: "Méfait à définir",
  232: "Méfait à définir",
  233: "Méfait à définir",
  234: "Méfait à définir",
  235: "Méfait à définir",
  236: "Méfait à définir",
  237: "Méfait à définir",
  238: "Méfait à définir",
  239: "Méfait à définir",
  240: "Méfait à définir",
  241: "Méfait à définir",
  242: "Méfait à définir",
  243: "Méfait à définir",
  244: "Méfait à définir",
  245: "Méfait à définir",
  246: "Méfait à définir",
  247: "Méfait à définir",
  248: "Méfait à définir",
  249: "Méfait à définir",
  250: "Méfait à définir",
  251: "Méfait à définir",
  252: "Méfait à définir",
  253: "Méfait à définir",
  254: "Méfait à définir",
  255: "Méfait à définir",
  256: "Méfait à définir",
  257: "Méfait à définir",
  258: "Méfait à définir",
  259: "Méfait à définir",
  260: "Méfait à définir",
  261: "Méfait à définir",
  262: "Méfait à définir",
  263: "Méfait à définir",
  264: "Méfait à définir",
  265: "Méfait à définir",
  266: "Méfait à définir",
  267: "Méfait à définir",
  268: "Méfait à définir",
  269: "Méfait à définir",
  270: "Méfait à définir",
  271: "Méfait à définir",
  272: "Méfait à définir",
  273: "Méfait à définir",
  274: "Méfait à définir",
  275: "Méfait à définir",
  276: "Méfait à définir",
  277: "Méfait à définir",
  278: "Méfait à définir",
  279: "Méfait à définir",
  280: "Méfait à définir",
  281: "Méfait à définir",
  282: "Méfait à définir",
  283: "Méfait à définir",
  284: "Méfait à définir",
  285: "Méfait à définir",
  286: "Méfait à définir",
  287: "Méfait à définir",
  288: "Méfait à définir",
  289: "Méfait à définir",
  290: "Méfait à définir",
  291: "Méfait à définir",
  292: "Méfait à définir",
  293: "Méfait à définir",
  294: "Méfait à définir",
  295: "Méfait à définir",
  296: "Méfait à définir",
  297: "Méfait à définir",
  298: "Méfait à définir",
  299: "Méfait à définir",
  300: "Méfait à définir",
  301: "Méfait à définir",
  302: "Méfait à définir",
  303: "Méfait à définir",
  304: "Méfait à définir",
  305: "Méfait à définir",
  306: "Méfait à définir",
  307: "Méfait à définir",
  308: "Méfait à définir",
  309: "Méfait à définir",
  310: "Méfait à définir",
  311: "Méfait à définir",
  312: "Méfait à définir",
  313: "Méfait à définir",
  314: "Méfait à définir",
  315: "Méfait à définir",
  316: "Méfait à définir",
  317: "Méfait à définir",
  318: "Méfait à définir",
  319: "Méfait à définir",
  320: "Méfait à définir",
  321: "Méfait à définir",
  322: "Méfait à définir",
  323: "Méfait à définir",
  324: "Méfait à définir",
};

export function getCardMefait(id: number): string {
  return CARD_MEFAITS[id] ?? "Méfait à définir";
}

