/**
 * Mapping numéro de carte → texte du méfait.
 * Ce fichier est la source unique pour les descriptions de méfaits.
 * Remplir chaque entrée avec le texte fourni par l utilisateur.
 */

export const CARD_MEFAITS: Record<number, string> = {
  1: "Ticket au prochain criminel",
  2: "Ticket au prochain criminel",
  3: "Ticket au prochain criminel",
  4: "Ticket au prochain criminel",
  5: "Ticket au prochain criminel",
  6: "Ticket au prochain criminel",
  7: "Ticket au prochain criminel",
  8: "Ticket au prochain criminel",
  9: "Ticket au prochain criminel",
  10: "Ticket au prochain criminel",
  11: "Ticket au prochain criminel",
  12: "Ticket au prochain criminel",
  13: "Ticket au prochain criminel",
  14: "Ticket au prochain criminel",
  15: "Ticket au prochain criminel",
  16: "Ticket au prochain criminel",
  17: "Ticket au prochain criminel",
  18: "Ticket au prochain criminel",
  19: "Ticket au prochain criminel",
  20: "Ticket au prochain criminel",
  21: "Ticket au prochain criminel",
  22: "Ticket au prochain criminel",
  23: "Ticket au prochain criminel",
  24: "Ticket au prochain criminel",
  25: "Ticket au prochain criminel",
  26: "Ticket au prochain criminel",
  27: "Ticket au prochain criminel",
  28: "Ticket au prochain criminel",
  29: "Ticket au prochain criminel",
  30: "Ticket au prochain criminel",
  31: "Ticket au prochain criminel",
  32: "Ticket au prochain criminel",
  33: "Ticket au prochain criminel",
  34: "Ticket au prochain criminel",
  35: "Ticket au prochain criminel",
  36: "Ticket au prochain criminel",
  37: "Ticket au prochain criminel",
  38: "Ticket au prochain criminel",
  39: "Ticket au prochain criminel",
  40: "Ticket au prochain criminel",
  41: "Ticket au prochain criminel",
  42: "Ticket au prochain criminel",
  43: "Ticket au prochain criminel",
  44: "Ticket au prochain criminel",
  45: "Ticket au prochain criminel",
  46: "Ticket au prochain criminel",
  47: "Ticket au prochain criminel",
  48: "Ticket au prochain criminel",
  49: "Ticket au prochain criminel",
  50: "Ticket au prochain criminel",
  51: "Ticket au prochain criminel",
  52: "Ticket au prochain criminel",
  53: "Ticket au prochain criminel",
  54: "Ticket au prochain criminel",
  55: "Ticket au prochain criminel",
  56: "Ticket au prochain criminel",
  57: "Ticket au prochain criminel",
  58: "Ticket au prochain criminel",
  59: "Ticket au prochain criminel",
  60: "Ticket au prochain criminel",
  61: "Ticket au prochain criminel",
  62: "Ticket au prochain criminel",
  63: "---",
  64: "---",
  65: "---",
  66: "---",
  67: "---",
  68: "---",
  69: "---",
  70: "---",
  71: "---",
  72: "---",
  73: "---",
  74: "---",
  75: "---",
  76: "Tu connais par cœur les paroles de la chanson Gangnam Style",
  77: "Ticket au prochain criminel",
  78: "Tu es partis acheté du lait mais t'es quand même revenu à la maison",
  79: "Tu cherches ton téléphone… avec ton téléphone dans la main",
  80: "Ton bodycount mérites d'être récompensé",
  81: "En karaoké, tu chantes mal, personne t'écoutes mais au moins tes saoul mort à la fin",
  82: "T'es tellement pauvre que te donner un autre ticket te ferais tomber en depression post-partum avec des effets post-traumatique",
  83: "On manquait de papier pour te donner un ticket",
  84: "Pas de ticket cette année, gentille petite chose, tu veux un bisou avec ça ?",
  85: "Tu es respectueux, jovial, souriant, par contre tu gosses tout le monde",
  86: "Tu n'as pas encore fais de jokes douteuses sur la mère de tes amis",
  87: "Vu que tu prends ton ritalin à chaque jours, ca mérite d'être une bonne action",
  88: "Car tu as compris l'utilité de virer tes bobettes de bord pour eviter du lavage",
  89: "Tu as vomis sur les passager arrière du Goliath à la ronde, c'était une mauvaise journée, mais au moins pas de ticket hein ?",
  90: "Car tu connais le nombre d'orteils de Toutânkhamon",
  91: "Tu as reussis à avoir un rendez-vous médicale après 6 ans d'attente",
  92: "Bravo pour avoir lacher l'école à 15 ans",
  93: "Car tu as été gentil pour Noel",
  94: "Tu n'as pas fais de cadeau de Noel cette année pour économiser de l'argent et acheter un truc inutile",
  95: "Le policier savait pas lire",
  96: "Tu fais pitié",
  97: "Tu prends du café 2,2 comme quelqu'un de normal et civilié",
  98: "Tu recycle comme un citoyen ecolo, intelligent et qui aime la soumission agressive",
  99: "Tu fais ta vaiselle comme une personne responsable, attentionné des autres et serviable pour le système qui te nourris et te loge",
  100: "Tu as chier comme jamais mais au moins ca sentait rien",
  101: "Tu as manifesté contre le referendum",
  102: "Tu as écouté ta mère quand elle te disais toujours non car elle t'aimais pas",
  103: "Tu as envoyé 5cents pour la fondations Tim Bits",
  104: "Bravo tu as gagné au 649, en 2006, tu as jamais réclamé ton dû car tu avais perdu ton billet",
  105: "Tu mets pas tes clignotant comme un citoyen avec du respect des codes de la routes",
  106: "Tu juges silencieusement les gens… puis tu culpabilises et ensuite tu te rends compte que t'es seul, pas d'amis, pas de yeux",
  107: "Tu crois que la guerre dans le monde est une bonne chose quand c'est fait avec amour et dignité",
  108: "Tu vas au gym pour cruizer en esperant que quelqu'un t'aime",
  109: "Tu as permis a un esclave d'avoir un bain 1 fois par mois",
  110: "Tu as porter un masque dans ton char en étant seul durant le covid, et tu le fais encore aujourd'hui",
  111: "Tu as partie une secte mais au moins t'es enregistrer au registre des entreprises",
  112: "Ton dossier était clean, à part en 1992 quand tu as acheter 42 guns sur le dark web mais sa passe",
  113: "Tu conduis un char électrique",
  114: "Tu conduis un bicycle et tu prends les rues au lieu des pistes cyclabe",
  115: "Ta schizophrénie sévère est un atout pour être un bon citoyen",
  116: "Je t'aime",
  117: "Pour t'être farcis une dinde, premier degré, c'est hot",
  118: "T'aime la poutine normal, pas d'ajout, t'es un civil respectable",
  119: "Pour avoir resister à un toutou avec des trous",
  120: "Pour avoir payer un pot de vins au policier en avance sexuel",
  121: "Écoute, l'inflation frappe fort, t'es dans marde, on te laisse une chance",
  122: "Pour avoir avoué que tu aimais te gargariser la gorge avec de l'urine",
  123: "Pour avoir effacer ton disque dur avec des trucs louche dedans",
  124: "Pour t'avoir réveiller comme un bon citoyen durant un Alerte Amber et avoir rien fait à part chialer",
  125: "Car tu pensais que le mush pouvait te donner des ailes, t'es mort, mais au moins ta pub pour Redbull a marché",
  126: "Tu avais des rêves, t'es rendu pauvre, triste, suicidaire, mais au moins tu joues à un jeu drôle, tiens cadeau",
  127: "Tu as reussit ton examen de conduite après ton 69e échec",
  128: "Parce que tu t'appelles Chantale",
  129: "Tu crois en la réincarnation, mais seulement s'il te manque des chromosomes",
  130: "---",
  131: "---",
  132: "---",
  133: "---",
  134: "---",
  135: "---",
  136: "---",
  137: "---",
  138: "---",
  139: "---",
  140: "---",
  141: "---",
  142: "---",
  143: "---",
  144: "---",
  145: "---",
  146: "---",
  147: "---",
  148: "---",
  149: "---",
  150: "---",
  151: "---",
  152: "---",
  153: "---",
  154: "---",
  155: "---",
  156: "---",
  157: "---",
  158: "---",
  159: "---",
  160: "---",
  161: "---",
  162: "---",
  163: "---",
  164: "---",
  165: "---",
  166: "---",
  167: "---",
  168: "---",
  169: "---",
  170: "---",
  171: "---",
  172: "---",
  173: "---",
  174: "---",
  175: "---",
  176: "---",
  177: "---",
  178: "---",
  179: "---",
  180: "---",
  181: "---",
  182: "---",
  183: "---",
  184: "---",
  185: "---",
  186: "---",
  187: "---",
  188: "---",
  189: "---",
  190: "---",
  191: "---",
  192: "---",
  193: "---",
  194: "---",
  195: "---",
  196: "---",
  197: "---",
  198: "---",
  199: "---",
  200: "---",
  201: "---",
  202: "---",
  203: "---",
  204: "---",
  205: "---",
  206: "---",
  207: "---",
  208: "---",
  209: "---",
  210: "---",
  211: "---",
  212: "---",
  213: "---",
  214: "---",
  215: "---",
  216: "---",
  217: "---",
  218: "---",
  219: "---",
  220: "---",
  221: "---",
  222: "---",
  223: "---",
  224: "---",
  225: "---",
  226: "---",
  227: "---",
  228: "---",
  229: "---",
  230: "---",
  231: "---",
  232: "---",
  233: "---",
  234: "---",
  235: "---",
  236: "---",
  237: "---",
  238: "---",
  239: "---",
  240: "---",
  241: "---",
  242: "---",
  243: "---",
  244: "---",
  245: "---",
  246: "---",
  247: "---",
  248: "---",
  249: "---",
  250: "---",
  251: "---",
  252: "---",
  253: "---",
  254: "---",
  255: "---",
  256: "---",
  257: "---",
  258: "---",
  259: "---",
  260: "---",
  261: "---",
  262: "---",
  263: "---",
  264: "---",
  265: "---",
  266: "---",
  267: "---",
  268: "---",
  269: "---",
  270: "---",
  271: "---",
  272: "---",
  273: "---",
  274: "---",
  275: "---",
  276: "---",
  277: "---",
  278: "---",
  279: "---",
  280: "---",
  281: "---",
  282: "---",
  283: "---",
  284: "---",
  285: "---",
  286: "---",
  287: "---",
  288: "---",
  289: "---",
  290: "---",
  291: "---",
  292: "---",
  293: "---",
  294: "---",
  295: "---",
  296: "---",
  297: "---",
  298: "---",
  299: "---",
  300: "---",
  301: "---",
  302: "---",
  303: "---",
  304: "---",
  305: "---",
  306: "---",
  307: "---",
  308: "---",
  309: "---",
  310: "---",
  311: "---",
  312: "---",
  313: "---",
  314: "---",
  315: "---",
  316: "---",
  317: "---",
  318: "---",
  319: "---",
  320: "---",
  321: "---",
  322: "---",
  323: "---",
  324: "---",
};

export function getCardMefait(id: number): string {
  return CARD_MEFAITS[id] ?? "---";
}

